export const socketAuth = {
  PENDING: '_PENDING',
  CONNECTED: '_CONNECTED',
  REJECTED: '_REJECTED',
  DISCONNECTED: '_DISCONNECTED',
};

export const socket = {
  CONNECTING: 'CONNECTING_TO_SERVER',
};

export const user = {
  SET_USER: 'SET_CURRENT_USER',
  SET_USERS: 'SET_LIST_OF_USERS',
  SET_USERS_STATUS: 'SET_USERS_STATUS',
};

export const chat = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  SET_MESSAGES: 'SET_PRE_MESSAGES',
};

export const snackbar = {
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  HIDE_SNACKBAR: 'HIDE_SNACKBAR',
};